# -*- coding: utf-8 -*-
"""Ejemplo_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13mGehW0rpLMW2jh-28GgAo4zqjGU__c4

**Condicionales**

un condicional puede ser simple o doble

EJ:
"""

n= 5345258345
Res = n % 2
if Res == 0:
  print(n, "es par")
else:
  print(n, "es impar ")